require("../src/serverless/handlers/cachePosts/initialized.js");
require("../src/serverless/handlers/facebookAuthCallback/initialized.js");
require("../src/serverless/handlers/facebookAuthRedirect/initialized.js");
require("../src/serverless/handlers/getPosts/initialized.js");
require("../src/serverless/handlers/getPostsRss/initialized.js");
require("../src/serverless/handlers/instagramAuthCallback/initialized.js");
require("../src/serverless/handlers/instagramAuthRedirect/initialized.js");
require("../src/serverless/handlers/twitterAuthCallback/initialized.js");
require("../src/serverless/handlers/twitterAuthRedirect/initialized.js");
module.exports.default = module.exports;
