import {CampaignLink, ConnectedHelloBear, EmailLink, LeftDescriptionSection} from "@randy.tarampi/jsx";
import PropTypes from "prop-types";
import React, {Fragment} from "react";

export const LetterIntro = ({contentConfiguration}) => {
    return <LeftDescriptionSection
        labelNode={<h3 className="printable-section__label">
            <ConnectedHelloBear textEffect={true} id="letter-intro-hello-bear"/>
        </h3>}
        descriptionNode={<Fragment>
            <p>
                <span className="text">That's a bear waving hello. They're a fixture in every <CampaignLink
                    href="https://github.com/randytarampi/me/search?q=%CA%95%E2%80%A2%E1%B4%A5%E2%80%A2%CA%94&unscoped_q=%CA%95%E2%80%A2%E1%B4%A5%E2%80%A2%CA%94">codebase I touch</CampaignLink></span>
            </p>
        </Fragment>}
        {...contentConfiguration.contentProps}
        type={contentConfiguration.contentKey}
        printableType="letter"
    >
        <p className="letter-intro__content">
            {
                contentConfiguration.contentProps.intro || <Fragment>
                    I hope this letter finds you well. I'm a forthright and honest guy, so I'll just tell you right now
                    that <CampaignLink
                    href="https://github.com/randytarampi/me/tree/master/packages/letter#readme"
                    text="this letter was autogenerated"/>. No disrepect intended of course — your time is
                    valuable and so is mine, and I figured that since this is an application for a software development
                    role I'd develop some software to build this letter (and my <CampaignLink
                    href="https://github.com/randytarampi/me/tree/master/packages/resume#readme" text="résumé"/> too).
                </Fragment>
            }
        </p>
        <p className="letter-intro__content">
            Give this a shot and keep reading — if I get so much as a chuckle out
            of you please <EmailLink useBranding={false} subject="I read your cover letter!">let me know</EmailLink>, if
            only to hear that someone actually reads these.
        </p>
    </LeftDescriptionSection>;
};

LetterIntro.propTypes = {
    letter: PropTypes.object.isRequired,
    contentConfiguration: PropTypes.object.isRequired,
};

export default LetterIntro;
