#!/usr/bin/env bash

set -e

BRANCH='gh-pages'
REPOSITORY=`mktemp -d /tmp/resume.XXXXXX`
BUILD='public/'

success() {
  echo -e "\033[32;1m$1"
}

error() {
  echo -e "\033[31;1m$1"
}

echo "==> Verifying build environment..."

if [ -z "$GH_TOKEN" ]; then
  error "Environment variable GH_TOKEN does not exist. Stopping deploy."
  exit 1
fi

if [ -z "$TRAVIS_BRANCH" ]; then
  error "Environment variable TRAVIS_BRANCH does not exist. Stopping deploy."
  exit 1
fi

if [ -z "$TRAVIS_COMMIT" ]; then
  error "Environment variable TRAVIS_COMMIT does not exist. Stopping deploy."
  exit 1
fi

if [ ! -d $BUILD ]; then
  error "Documentation does not exist. Stopping deploy."
  exit 1
fi

echo "==> Syncing updated documentation..."
git clone --branch $BRANCH https://$GH_TOKEN@github.com/eddywashere/resume $REPOSITORY > /dev/null 2>&1
rsync -rt --del --exclude=".git" $BUILD $REPOSITORY

echo "==> Pushing updated documentation to GitHub Pages..."
cd $REPOSITORY

if [ "$TRAVIS_BRANCH" != "master" ]; then
  success "Not building master branch. Skipping deploy."
  exit 0
fi

if [ -z "$(git status --porcelain)" ]; then
  success "No documentation changes to publish. Skipping deploy."
  exit 0
fi

git add --all
git config user.name "eddywashere"
git config user.email "edward.d.hernandez@gmail.com"
git commit --message "build(travis): publish build for $TRAVIS_COMMIT"
git push --quiet origin gh-pages > /dev/null 2>&1

success "Successfully published site for commit: $TRAVIS_COMMIT!"
