name: deploy (service)

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      environment:
        description: 'The deployment environment'
        required: true
        default: prd
        type: choice
        options:
          - dev
          - prd

concurrency:
  group: deploy-service-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy-service:
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'prd' }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      NODE_ENV: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'prd' }}
    steps:
      - name: Run `git checkout`
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node@24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        env:
          YARN_ENABLE_HARDENED_MODE: false
        run: yarn install

      - name: Configure AWS credentials from secrets
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy service
        run: cd packages/service && yarn run deploy
