name: deploy (GitHub Pages)

on:
  workflow_call:
    inputs:
      application_name:
        description: 'The application to deploy'
        required: false
        default: www
        type: string
      deployment_environment:
        description: 'The targeted `DEPLOYMENT_ENVIRONMENT`'
        required: false
        default: dev
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      GH_PAGES_DEPLOYMENT_TOKEN:
        required: true

  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      application_name:
        description: 'The application to deploy'
        required: true
        default: www
        type: choice
        options:
          - www
          - jsonresume-theme
      deployment_environment:
        description: 'The targeted `DEPLOYMENT_ENVIRONMENT`'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prd

concurrency:
  group: deploy-pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy__www--dev:
    if: ${{ github.event_name != 'push' && (github.event.inputs.deployment_environment || inputs.deployment_environment || 'dev') == 'dev' && (github.event.inputs.application_name || inputs.application_name || 'www') == 'www' }}
    uses: ./.github/workflows/deploy.pages.reusable.yml
    with:
      application_name: ${{ github.event.inputs.application_name || inputs.application_name || 'www' }}
      deployment_environment: dev
      deployment_ref: ${{ github.sha }}
      adjust_docs_for_dev: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GH_PAGES_DEPLOYMENT_TOKEN: ${{ secrets.GH_PAGES_DEPLOYMENT_TOKEN }}

  deploy__www--prd:
    if: ${{ github.event_name == 'push' || (github.event.inputs.deployment_environment || inputs.deployment_environment || 'dev') == 'prd' }}
    uses: ./.github/workflows/deploy.pages.reusable.yml
    with:
      application_name: ${{ github.event.inputs.application_name || inputs.application_name || 'www' }}
      deployment_environment: ${{ github.event_name == 'push' && 'prd' || (github.event.inputs.deployment_environment || inputs.deployment_environment || 'prd') }}
      deployment_ref: ${{ github.event_name == 'push' && github.ref_name || github.sha }}
      adjust_docs_for_dev: false
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GH_PAGES_DEPLOYMENT_TOKEN: ${{ secrets.GH_PAGES_DEPLOYMENT_TOKEN }}
