name: release

on:
  push:
    branches:
      - master

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  packages: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run `git checkout`
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node@24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Version packages
        run: npx lerna version --conventional-commits --yes

      - name: Publish packages
        run: npx lerna publish from-git --yes
